/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcontrolmanager;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Everdt
 */
public class View extends javax.swing.JFrame {

    public StockControlManager sCManager;
    String medication[] = {"NEVIRAPINE", "STAVUDINE", "ZIDOTABINE"};
    public View(StockControlManager sCManager) {
        initComponents();
        
        this.sCManager = sCManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        clinicCB = new javax.swing.JComboBox();
        checkStockBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lowStockBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        dbLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane1.setViewportView(taOutput);

        clinicCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Clinic" }));
        clinicCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicCBActionPerformed(evt);
            }
        });

        checkStockBtn.setText("Check Stock");
        checkStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStockBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Update Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lowStockBtn.setText("Stock Running Low");
        lowStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStockBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Clear Area");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Start by choosing a clinic:");

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkStockBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lowStockBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clinicCB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(quitBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dbLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clinicCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkStockBtn)
                    .addComponent(jButton2)
                    .addComponent(lowStockBtn))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clinicCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clinicCBActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clinicCB.setSelectedIndex(0);
        taOutput.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
         try {
            sCManager.dbcon.close();
            sCManager.connStatement.close();
            sCManager.lowStatement.close();
            sCManager.searchStatement.close();
            sCManager.updateStatement.close();
        } catch (SQLException ex) {
            System.err.println("Error closing connection" + ex);
        } finally {
            System.exit(0);
        }
    }//GEN-LAST:event_quitBtnActionPerformed

    private void checkStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStockBtnActionPerformed
        int activeClinic = clinicCB.getSelectedIndex();
        if (activeClinic == 0) {
            JOptionPane.showMessageDialog(null, "Please select a Clinic", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            sCManager.checkDB(activeClinic);
        }
    }//GEN-LAST:event_checkStockBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            int activeClinic = clinicCB.getSelectedIndex();
            if (activeClinic == 0) {
                JOptionPane.showMessageDialog(null, "Please choose a Clinic", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String medicationName = (String) JOptionPane.showInputDialog(null, "Please provide the name of the medication you want to update", "",
                        JOptionPane.QUESTION_MESSAGE, null, medication, medication[0]).toString().toUpperCase();
                int newQty = Integer.parseInt(JOptionPane.showInputDialog("What is the new value for the stock quantity"));
                sCManager.updateStockDB(activeClinic, medicationName, newQty);

            }
        } catch (HeadlessException ex) {
            System.err.println("Error performing the update function: " + ex);
        } catch (NullPointerException ex) {
            System.err.println("Update operation cancelled: " + ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid quantity entered, please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error performing the update function: " + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lowStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStockBtnActionPerformed
        sCManager.stockRunningLow();
    }//GEN-LAST:event_lowStockBtnActionPerformed

  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton checkStockBtn;
    public javax.swing.JComboBox clinicCB;
    public javax.swing.JLabel dbLabelStatus;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton lowStockBtn;
    public javax.swing.JButton quitBtn;
    public javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
